### ISSUE TITLE
Running WS connection in the background

### ISSUE THREAD

**Issue by ookami-kb** [solana-mobile/mobile-wallet-adapter#108]
Hi, since the main transport protocol is WebSockets, how will it ensure that the connection would be running in the background seamlessly (at least one part of wallet <-> dapp communication would be in the background)?

It can be more of an issue for the iOS platform since there are much stricter requirements for apps running in the background, but even in Android, there can be different restrictions depending on Android versions and vendor-specific OS updates.

**Comment by sdlaver** [comment]
For Android, we have an open issue, https://github.com/solana-mobile/mobile-wallet-adapter/issues/97, to track this. The fix will likely involve a background service in clientlib to keep the session alive during the context switch.

For iOS, there are still a few TODOs in the spec, of which this is one.

Since there are already open items for each, I'm going to close this issue, but please re-open if there is additional work that I didn't capture here.

**Comment by ookami-kb** [comment]
> The fix will likely involve a background service in clientlib to keep the session alive during the context switch.

Do you mean _foreground_ service? IIRC, _background_ service still has limitations and can be e.g. killed by OS. With foreground services, though, how would it be possible for _web_ dapp to use one?

**Comment by sdlaver** [comment]
Yep, while BG services can still be killed, but should be only when there's memory pressure and a need to do so, or it has run for a substantial amount of time. MWA connections should be time-bound (since they necessarily involve interactions with the wallet app, after which a context switch to the dapp will occur). 

We are absolutely at the mercy of the platform here, but any use of MWA in a general sense will need to be tolerant of occasional failure and retry, in case a remote scenario is being used (which suffer from failure modes outside of the control of the device, such as network interruption).

**Comment by ookami-kb** [comment]
Yeah, I agree, it's more of a concern for iOS, looking forward to specs for it.
