### ISSUE TITLE
[spec feedback] Wallet should be able to easily verify dApps

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#206]
From the screenshots below, it was a bit confusing to me about how the dApp verification process will work if the dApp is in the browser. 

In the [Dapp identity verification](https://solana-mobile.github.io/mobile-wallet-adapter/spec/spec.html#dapp-identity-verification) section I read about how dApp verification could work — but it seems a bit complex / confusing / error prone. It sounds like the wallet app has to create a browser context where it can request the dApps signature somehow? (Idk if that's right.)

Is there an easier way we could do this? Is it possible to include a verified requesting URL in the deep link? It sounds like vanilla Android doesn't provide it but maybe that can be added to this fork?

---

![F956232F-0D76-4833-A210-0E771E18B357](https://user-images.githubusercontent.com/1319079/183273538-51528405-79da-4d69-b5f5-6e63135f97cf.jpg)
![IMG_4175](https://user-images.githubusercontent.com/1319079/183273543-7c3e251b-7b67-4a52-8d1c-b673d614ea0e.jpeg)

**Comment by steveluscher** [comment]
I’ll leave this one to @sdlaver to answer. He’s so good at it.

**Comment by sdlaver** [comment]
Identity verification is the [most complex part of the spec](https://solana-mobile.github.io/mobile-wallet-adapter/spec/spec.html#dapp-identity-verification).

On Android, for native dapps, it is easy - any invocation of the wallet via a `startActivityForResult` can be verified. The same does not extend to web dapps, however, hence the relatively complex scheme to allow the wallet app to make use of Chrome Custom Tabs to temporarily become a trusted actor in the browser sandbox, and for a cooperating web page to perform origin attestation using `postMessage` from the dapp.

@steveluscher and I have prototyped this out sufficiently to prove it will work, but the implementation is not complete. It's part of the spec because of the important trust & safety role that wallets provide to users. That said, it's a self-contained sub-section of the protocol, and if wallets are able to provide sufficient trust & safety to users through other means, MWA would still work fine if a wallet did not implement the web dapp identity verification.

> Is there an easier way we could do this? Is it possible to include a verified requesting URL in the deep link? It sounds like vanilla Android doesn't provide it but maybe that can be added to this fork?

Sadly, myself and several others were unable to come up with anything for web dapps that is easier than this. We could absolutely add something to Saga to enable this, but Mobile Wallet Adapter is intended to work far beyond Saga - on every Android device (and eventually every iOS device too). This limits us to stock Android, where Chrome does not provide any stock mechanism to verify the identity of a web dapp.

With all that said, here is a summary of technical details of the identity attestation scheme:
- Wallet uses a Chrome Custom Tab to assume the identity of a domain (for e.g., android-app://foobarwallet.io) with Digital Asset Linjs. It can then `postMessage` to a web page hosted on the domain (for e.g. https://foobarwallet.io/attestation). The web page can be static - it is responsible for receiving the `postMessage` from the wallet app, verifying the identity (which is trustworthy, since the origin is delivered by the Chrome browser).
- The attestation web page generates a keypair, stores the private half in local storage, and gives the public half to the wallet app
- Later, the web dapp can `postMessage` to this same page (or a related one). The attestation page can use the private key (only available in local storage) to sign the incoming origin, plus a related challenge value (to prevent replay attacks). This can be transmitted via the WebSocket protocol back to the wallet, which is able to verify that the attestation is authentic, using the public key previously obtained via the Chrome Custom Tab.

The Chrome Custom Tab only needs to be used once, to retrieve the public key of the attestation page in a trusted manner.

**Comment by vpontis** [comment]
> but Mobile Wallet Adapter is intended to work far beyond Saga - on every Android device

Ah got it, I know you mentioned this but I didn't internalize that. It definitely makes the design space harder. 

Thanks for writing this up! I worry with the `/attestation` route that it may be hard for some dApp developers to create that verification page and then will try to get wallets to not require that verification...

**Comment by sdlaver** [comment]
@vpontis the intention here would be for that page to be provided by wallets, not by dapps. You can think of it as extending the wallet's execution context inside the browser sandbox - the wallet establishes a keypair between the app and the attestation page in the browser, and then dapps make use of that attestation page (via `postMessage` calls) to request the origin be signed using that keypair.

**Comment by sdlaver** [comment]
Closing due to no additional activity for 7+ days
