### ISSUE TITLE
[spec feedback] Network per method

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#207]
Right now the spec has the dApp authenticate with the network and then it uses the same network every time the auth token is requested. 

I propose that every request that is relevant to a network should include a network parameter. 

This is simpler because:

1. it allows an dApp to use one auth token for multiple networks (this is useful if you let the user toggle networks in your app)
2. it doesn't require the wallet app to remember the mapping of auth token <> session
3. it will require fewer websockets if you are doing things on multiple networks

**Comment by steveluscher** [comment]
This is how we had it initially. Then we changed it.

The idea behind elevating the cluster to the level of the authorization is this:

1. it’s nonsensical to expect that an authorization for one cluster is semantically equivalent in any way to an authorization for a different cluster, because the assets you hold on each cluster are completely distinct. The same pubkey on two different clusters is no more similar in terms of its holdings than two different pubkeys on the same cluster.
2. We want to avoid scenarios where granting authorization to use a dApp on devnet unexpectedly escalates to mainnet use without requiring the user to _re_authorize the dApp. Imagine that you’re using a devnet beta of a dApp for fun, and then some time later they surreptitiously start asking you for authorizations on mainnet, _but you don’t notice_.
