### ISSUE TITLE
[spec feedback] Sign and send txs mode (serial / parallel)

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#210]
It would be nice if the `sign_and_send_transactions` request specified if the transactions are dependent on each other and should be sent serially or if they should be sent in parallel. 

If the transactions are sent serially, then it would be nice for the wallet to replace the blockhash to ensure that the blockhahes aren't too old.

**Comment by sdlaver** [comment]
> If the transactions are sent serially, then it would be nice for the wallet to replace the blockhash to ensure that the blockhahes aren't too old.

The wallet can do anything it likes to the transaction before sending it, but replacing the blockhash as a general solution runs into the multi-sig problem - the transaction may arrive at the wallet partially signed, and any modifications would invalidate those other signatures.

> It would be nice if the sign_and_send_transactions request specified if the transactions are dependent on each other and should be sent serially or if they should be sent in parallel.

Since the communication channel does not need to be torn down in between subsequent transaction requests, serial execution can be achieved with back-to-back calls to `sign_and_send_transactions`.

**Comment by sdlaver** [comment]
Closing due to no additional activity for 7+ days
