### ISSUE TITLE
[spec feedback] Do dapps need to pick a port?

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#212]
<img width="775" alt="CleanShot 2022-08-06 at 23 32 08@2x" src="https://user-images.githubusercontent.com/1319079/183273930-bcf63912-21e1-43ca-b986-5f9e883a4868.png">

Is it possible there are going to be issues with two dApps wanting to use the same port?

Is there any way we can avoid having dApps have to pick a port? It feels kinda odd.

**Comment by steveluscher** [comment]
Never. Wallet sessions last for as long as the app context switch, then close. You can never be in the middle of two at the same time.

1. Take some action in a dApp
2. Session opens, on random port and app context switches to wallet
3. User does stuff in wallet
4. When they’re done, port closes and app context switches back to dApp

**Comment by vpontis** [comment]
Got it — why pick a random port? Why not just say that 50000 is the Solana MWA port and fix it?

**Comment by steveluscher** [comment]
I think it used to be a defence against replay attacks but maybe it’s been obviated by the initialization vector we added later. @slaver will know for sure.

**Comment by sdlaver** [comment]
It's a defence measure against a Denial of Service attack. Any malicious app (dapp, wallet, or otherwise) could squat on that port number, and prevent your wallet from providing services to dapps. The background process reapers on Android would make this somewhat difficult, but I wouldn't want to rely on that platform behavior to protect the protocol. Having the dapp choose a random port from the dynamic range doesn't guarantee that collisions cannot occur, but it does remove the element of maliciousness from it.
