### ISSUE TITLE
Long timeout cooldown after failed Intent disambiguation dialog

### ISSUE THREAD

**Issue by Michaelsulistio** [solana-mobile/mobile-wallet-adapter#489]
**Describe the bug**
When a dApp attempts to authorize and connect to a wallet, the first step opens an Intent Disambiguation Dialog, where the user chooses a wallet to connect to. If the user clicks outside of this dialog, thus closing the dialog, they are subject to a long timeout/cooldown before they can start another connect attempt.

I have noticed so far only on our React Native Sample apps, but not `fakedapp` which is Kotlin.

**To Reproduce**
1. On RN Scaffold dApp click Connect to open disambiguation dialog
2. click outside of disambiguation dialog
3. observe that you cannot click connect again until after a 10-25 seconds.

**Expected behavior**
On `fakedapp` you are able to immediately click connect again and fire up the disambiguation dialog again. This is expected behavior.

**Screenshots**
Repro video from CandyPay developer working on their React Native/Expo app:
https://github.com/solana-mobile/mobile-wallet-adapter/assets/18451967/11c92f04-4979-4533-b851-ef1e018f14cd

**Smartphone (please complete the following information):**
 - Device: Any Android Emulator
**Additional context**

**Comment by Funkatronics** [comment]
This can also be observed on the web, using our `example-web-app`. On the web, this is a tough problem to fix, because there is no way to detect if the disambiguation dialog is closed. I did an investigation to see if we could grab the touch or some kind of window state change but there is no event that is reliably thrown in this case. Because the webpage is still open and the disambiguation dialog is drawn on top, there is no window state change that could be used to detect when the user backs out of the wallet selection dialog. 

In react native, this should be fixable. We should have some way of detecting either the canceling of the disambiguation or the return of the app to the foreground. the question is where to implement this fix - can this be handling in our libraries or will dapps themselves need to handle this case?

**Comment by Michaelsulistio** [comment]
Why isn't this an issue with Kotlin dApps? Is it because there's a way for the Kotlin code to see when the disambiguation is cancelled?

Ideally we just fix this in our own RN library.
